# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20171215_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='front_image_url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
