# Generated by Django 2.1.7 on 2019-03-08 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=1024)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=20)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=20)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=20)),
                ('people_count', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('description', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('description', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='journeys.Journey')),
            ],
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_type', models.IntegerField(choices=[(0, 'walk'), (1, 'public transport'), (2, 'private transport'), (3, 'airplane')], default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits', to='journeys.Journey')),
            ],
        ),
    ]
