# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('people_count', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=20)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=20)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=20)),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=1024)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('location', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_journey', to='journeys.Journey')),
            ],
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_type', models.IntegerField()),
                ('description', models.TextField()),
                ('position', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transit_end_milestone', to='journeys.Milestone')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_journey', to='journeys.Journey')),
                ('start_milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transit_start_milestone', to='journeys.Milestone')),
            ],
        ),
    ]
