# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transit',
            name='position',
        ),
        migrations.AlterField(
            model_name='journey',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='transit',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='transit',
            name='transit_type',
            field=models.IntegerField(choices=[(0, 'walk'), (1, 'public transport'), (2, 'private transport'), (3, 'airplane')], default=1),
        ),
    ]
