# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_auto_20171106_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transit',
            name='description',
            field=models.TextField(),
        ),
    ]
