# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 08:03
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_auto_20171107_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='location',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='location',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
