# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0004_auto_20171107_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transit',
            name='id',
        ),
        migrations.AlterField(
            model_name='journey',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='journeys.Journey'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='end_milestone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='end_milestone_of', to='journeys.Milestone'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits', to='journeys.Journey'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='start_milestone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='start_milestone_of', serialize=False, to='journeys.Milestone'),
        ),
    ]
